services:
  crash-crafts-game-sync:
    build: .
    ports:
      - "8080:8080"
    init: true
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - crash-crafts-game-sync-data:/data
      - crash-crafts-game-sync-config:/config
volumes:
  crash-crafts-game-sync-data:
  crash-crafts-game-sync-config:
